name: Release

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install tools
        run: rokit install

      - name: Publish
        run: wally publish
        env:
          WALLY_AUTH_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
